# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b51daf192b3c6342ce380860cd1994918f65de5d4a5332b1896ec7b1d7739d9515b1e32b10b1dd7dca9379818cdbb935d1c34ce32526e5d8b28683025d16812

test:
  secret_key_base: c58deaf9780b53a711cc1efc6b6a5c69562aa404ba3a1b8e9e8c2b912a2bfb295a59a4938a6a7fcfcac8a2930a7f517e8c0d1b1835549022e593c325fc277ce0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
